In [1]:
import pandas as pd

In [3]:
labels = ['a','b','c']
my_lst = [10,20,30]
my_arr = np.arange(3)
my_dict = {'a':10,'b':20,'c':30}

In [4]:
pd.Series(my_dict,index = my_lst)

10   NaN
20   NaN
30   NaN
dtype: float64

In [5]:
ser1 = pd.Series(['a','b','c'],[10,20,30])

In [6]:
ser2 = pd.Series(['c','d','e'],[30,40,50])

In [7]:
ser_sum = ser1 + ser2
ser_sum

10    NaN
20    NaN
30     cc
40    NaN
50    NaN
dtype: object

In [8]:
ser1[10]

'a'

In [9]:
my_arr

array([0, 1, 2])

In [10]:
my_arr = np.arange(9).reshape(3,3)
my_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
pd.Series(my_arr.flatten(),labels*3)

a    0
b    1
c    2
a    3
b    4
c    5
a    6
b    7
c    8
dtype: int32

In [12]:
import numpy as np

In [13]:
import pandas as pd

In [14]:
from numpy.random import randn

In [15]:
np.random.seed(101)

In [16]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [17]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [18]:
df [['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [19]:
df['W + Z'] = df['W'] + df['Z']
df

W         X         Y         Z     W + Z
A  2.706850  0.628133  0.907969  0.503826  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  1.257083
C -2.018168  0.740122  0.528813 -0.589001 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  1.143752
E  0.190794  1.978757  2.605967  0.683509  0.874303

In [20]:
df.drop('W + Z' , axis = 1,)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [21]:
df

W         X         Y         Z     W + Z
A  2.706850  0.628133  0.907969  0.503826  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  1.257083
C -2.018168  0.740122  0.528813 -0.589001 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  1.143752
E  0.190794  1.978757  2.605967  0.683509  0.874303

In [22]:
df.drop('W + Z' , axis = 1, inplace = True)

In [23]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [24]:
df['W']['E']

0.19079432237171562

In [25]:
df['new'] = df['W']+ df['X']
df['new']

A    3.334983
B    0.331800
C   -1.278046
D   -0.570177
E    2.169552
Name: new, dtype: float64

In [26]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [27]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [28]:
df['E']

KeyError: 'E'

In [29]:
df.loc['E']

W      0.190794
X      1.978757
Y      2.605967
Z      0.683509
new    2.169552
Name: E, dtype: float64

In [30]:
df.iloc[4]

W      0.190794
X      1.978757
Y      2.605967
Z      0.683509
new    2.169552
Name: E, dtype: float64

In [31]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [32]:
df.loc[['A','D'],['X','new']]

X       new
A  0.628133  3.334983
D -0.758872 -0.570177

In [33]:
df.iloc[[0,3],[1,4]]

X       new
A  0.628133  3.334983
D -0.758872 -0.570177

In [34]:
df.shape

(5, 5)

In [35]:
df.drop('new',axis = 1, inplace = True)

In [36]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [37]:
import numpy as np

In [38]:
import pandas as pd

In [39]:
from numpy.random import randn

In [40]:
np.random.seed(101)

In [41]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [42]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [43]:
booldf = df > 0

In [44]:
df[booldf]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [45]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [46]:
df[df>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [47]:
df[df<0]

W         X         Y         Z
A       NaN       NaN       NaN       NaN
B       NaN -0.319318 -0.848077       NaN
C -2.018168       NaN       NaN -0.589001
D       NaN -0.758872 -0.933237       NaN
E       NaN       NaN       NaN       NaN

In [48]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [49]:
df[df['X']>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
C -2.018168  0.740122  0.528813 -0.589001
E  0.190794  1.978757  2.605967  0.683509

In [50]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [51]:
df[df['Z']<0]['X']

C    0.740122
Name: X, dtype: float64

In [52]:
df[df['Z']<0][['W','X','Y','Z']]

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [53]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [54]:
df[(df['W']>0) & (df['Y']>1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [55]:
df[(df['W']>0) | (df['Y']>1)]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [56]:
resetexp = df

In [57]:
resetexp

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [58]:
resetexp.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [59]:
df['newind'] = ('ا ب پ ت ٹ').split()

In [60]:
df

W         X         Y         Z newind
A  2.706850  0.628133  0.907969  0.503826      ا
B  0.651118 -0.319318 -0.848077  0.605965      ب
C -2.018168  0.740122  0.528813 -0.589001      پ
D  0.188695 -0.758872 -0.933237  0.955057      ت
E  0.190794  1.978757  2.605967  0.683509      ٹ

In [61]:
df.set_index('newind')

W         X         Y         Z
newind                                        
ا       2.706850  0.628133  0.907969  0.503826
ب       0.651118 -0.319318 -0.848077  0.605965
پ      -2.018168  0.740122  0.528813 -0.589001
ت       0.188695 -0.758872 -0.933237  0.955057
ٹ       0.190794  1.978757  2.605967  0.683509

In [62]:
df['W'] >0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [63]:
df[df['W']>0]

W         X         Y         Z newind
A  2.706850  0.628133  0.907969  0.503826      ا
B  0.651118 -0.319318 -0.848077  0.605965      ب
D  0.188695 -0.758872 -0.933237  0.955057      ت
E  0.190794  1.978757  2.605967  0.683509      ٹ

In [64]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [65]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [66]:
df = pd.DataFrame(randn(6,2),hier_index,['A','B'])

In [67]:
df

A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [68]:
df.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [69]:
df

A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [70]:
df.index.names = ['Groups','Numbers']

In [71]:
df

A         B
Groups Numbers                    
G1     1        0.302665  1.693723
       2       -1.706086 -1.159119
       3       -0.134841  0.390528
G2     1        0.166905  0.184502
       2        0.807706  0.072960
       3        0.638787  0.329646

In [72]:
df.loc['G1']['A'].loc[1]

0.3026654485851825

In [73]:
df.loc['G2']['B'][2]

0.07295967531703869

In [74]:
df.loc['G2'].loc[2]['B']

0.07295967531703869

In [75]:
df

A         B
Groups Numbers                    
G1     1        0.302665  1.693723
       2       -1.706086 -1.159119
       3       -0.134841  0.390528
G2     1        0.166905  0.184502
       2        0.807706  0.072960
       3        0.638787  0.329646

In [76]:
df.xs(1, level = 'A', axis = 1)

TypeError: Index must be a MultiIndex

In [77]:
d = dict({'A' : [1,2,np.nan] , 'B' : [4,np.nan,np.nan], 'C' : [7,8,9]})
d

{'A': [1, 2, nan], 'B': [4, nan, nan], 'C': [7, 8, 9]}

In [78]:
df = pd.DataFrame(d)

In [79]:
df

A    B  C
0  1.0  4.0  7
1  2.0  NaN  8
2  NaN  NaN  9

In [80]:
df.dropna()

A    B  C
0  1.0  4.0  7

In [81]:
df.dropna(axis = 1)

C
0  7
1  8
2  9

In [82]:
df.dropna(thresh=2)

A    B  C
0  1.0  4.0  7
1  2.0  NaN  8

In [83]:
df.fillna(value='Filled Value')

A             B  C
0           1.0           4.0  7
1           2.0  Filled Value  8
2  Filled Value  Filled Value  9

In [86]:
df['A'].fillna(value = df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [87]:
import pandas as pd
# Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [88]:
data

{'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
 'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
 'Sales': [200, 120, 340, 124, 243, 350]}

In [89]:
df= pd.DataFrame(data)

In [90]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [97]:
byperson = df.groupby('Person')

In [98]:
byperson

In [100]:
byperson.sum()

Company  Sales
Person                
Amy        MSFT    340
Carl         FB    243
Charlie    GOOG    120
Sam        GOOG    200
Sarah        FB    350
Vanessa    MSFT    124

In [94]:
bysale = df.groupby('Sales')

In [96]:
bysale.sum()

Company   Person
Sales                 
120      GOOG  Charlie
124      MSFT  Vanessa
200      GOOG      Sam
243        FB     Carl
340      MSFT      Amy
350        FB    Sarah

In [101]:
bycomp = df.groupby('Company')

In [102]:
bycomp.sum()

Person  Sales
Company                   
FB        CarlSarah    593
GOOG     SamCharlie    320
MSFT     AmyVanessa    464

In [106]:
import pandas as pd
# Create dataframe
new_data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,'HELLO',243,350]}

In [107]:
ndf = pd.DataFrame(new_data)

In [108]:
ndf

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa  HELLO
4      FB     Carl    243
5      FB    Sarah    350

In [109]:
by_company = ndf.groupby('Company')

In [111]:
by_company

In [112]:
by_company.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [113]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [123]:
bycomp.describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [6]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [4]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [8]:
tdf = pd.DataFrame(randn(11,11),['A','B','C','D','E','F','G','H','I','J','K'],[1,2,3,4,5,6,7,8,9,10,11])
tdf

1         2         3         4         5         6         7   \
A -0.528855 -1.339012 -0.358002  0.665883 -0.305254 -0.223809  0.000702   
B  0.726393 -1.131447  1.096456 -0.662096 -0.884609  0.990676  0.890803   
C -0.980884  0.550466 -0.046505 -0.892247 -0.697425 -0.673490  1.122951   
D -1.695019  2.423163 -1.033440 -0.654005  0.065088 -0.498516 -0.472341   
E -0.074650 -0.645573 -0.397308 -0.657134 -0.075995  0.140716 -0.641675   
F -0.660843 -0.004983  0.094233  1.885990  0.761522  1.033483 -0.261177   
G -1.371857 -0.228785 -0.040474  1.007707 -1.078914 -0.496563  1.170513   
H -1.050312 -1.582260  1.358371 -0.443340 -0.869298 -2.112533  0.399140   
I -1.196804 -2.189584 -0.858733 -0.838474  0.828012  0.512048  0.115907   
J -0.379825  1.084752 -0.357906  0.544904 -0.996194 -0.058248 -0.353441   
K -0.500113 -2.002215  0.188410  0.155722 -0.395810 -2.451035 -0.748060   

         8         9         10        11  
A  1.514507  0.715421  1.207538  0.400500  
B -1.703259 -0.350748 -1.872115  0.446666  
C -0.521843  1.160574 -1.812306  0.085505  
D -0.419320  1.408027 -0.388506 -0.419259  
E -0.984723 -1.351489 -1.233983 -0.541679  
F  0.508451 -1.533382  0.778612  0.949263  
G  0.869204  0.675395  0.787881  0.326269  
H -0.525462  0.968225 -0.640774 -0.483559  
I -0.787790  2.015141 -0.542612 -1.048735  
J  1.086787  2.036971  1.365617 -0.932416  
K  0.088477 -0.405381  1.310794  1.641361

In [10]:
tdf.head(8)

1         2         3         4         5         6         7   \
A -0.528855 -1.339012 -0.358002  0.665883 -0.305254 -0.223809  0.000702   
B  0.726393 -1.131447  1.096456 -0.662096 -0.884609  0.990676  0.890803   
C -0.980884  0.550466 -0.046505 -0.892247 -0.697425 -0.673490  1.122951   
D -1.695019  2.423163 -1.033440 -0.654005  0.065088 -0.498516 -0.472341   
E -0.074650 -0.645573 -0.397308 -0.657134 -0.075995  0.140716 -0.641675   
F -0.660843 -0.004983  0.094233  1.885990  0.761522  1.033483 -0.261177   
G -1.371857 -0.228785 -0.040474  1.007707 -1.078914 -0.496563  1.170513   
H -1.050312 -1.582260  1.358371 -0.443340 -0.869298 -2.112533  0.399140   

         8         9         10        11  
A  1.514507  0.715421  1.207538  0.400500  
B -1.703259 -0.350748 -1.872115  0.446666  
C -0.521843  1.160574 -1.812306  0.085505  
D -0.419320  1.408027 -0.388506 -0.419259  
E -0.984723 -1.351489 -1.233983 -0.541679  
F  0.508451 -1.533382  0.778612  0.949263  
G  0.869204  0.675395  0.787881  0.326269  
H -0.525462  0.968225 -0.640774 -0.483559

In [11]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [16]:
df.sort_values('col2', inplace=True)
df

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [17]:
df.sort_index()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [18]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [19]:
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [20]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

In [21]:
pwd

'C:\\Users\\Amar Khaggah\\Downloads\\data science notes\\notebooks'

In [31]:
import pandas as pd
df = pd.read_excel('business-operations-survey-2023-CSV-notes.xlsx', sheet_name='Sheet1')
df.head()

Footnotes                                         Unnamed: 1  \
0         1  The Business Operations Survey samples busines...   
1         2  For more information about the number of busin...   
2         3  See DataInfo+ for questionnaires, and more exp...   
3         4  Business size is defined by rolling mean emplo...   
4         5  Results for the mining and electricity, gas, w...   

                                 Unnamed: 2  
0  BOS Series Data Collection  ̶  DataInfo+  
1           New Zealand business demography  
2                                 DataInfo+  
3                BOS Concepts  ̶  DataInfo+  
4                                       NaN

In [32]:
import pandas as pd
df = pd.read_excel('business-operations-survey-2023-CSV-notes.xlsx', sheet_name='Sheet2')
df.head()

0                                            Sheet 2  \
0  1  The Business Operations Survey samples busines...   
1  2  For more information about the number of busin...   
2  3  See DataInfo+ for questionnaires, and more exp...   
3  4  Business size is defined by rolling mean emplo...   
4  5  Results for the mining and electricity, gas, w...   

                                 Unnamed: 2  
0  BOS Series Data Collection  ̶  DataInfo+  
1           New Zealand business demography  
2                                 DataInfo+  
3                BOS Concepts  ̶  DataInfo+  
4                                       NaN

In [33]:
df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

In [38]:
df = df[0].head()

In [39]:
df

Bank Name           City         State   Cert  \
0  Republic First Bank dba Republic Bank   Philadelphia  Pennsylvania  27332   
1                          Citizens Bank       Sac City          Iowa   8758   
2               Heartland Tri-State Bank        Elkhart        Kansas  25851   
3                    First Republic Bank  San Francisco    California  59017   
4                         Signature Bank       New York      New York  57053   

                Aquiring Institution      Closing Date   Fund  
0  Fulton Bank, National Association    April 26, 2024  10546  
1          Iowa Trust & Savings Bank  November 3, 2023  10545  
2             Dream First Bank, N.A.     July 28, 2023  10544  
3          JPMorgan Chase Bank, N.A.       May 1, 2023  10543  
4                Flagstar Bank, N.A.    March 12, 2023  10540

In [40]:
df.to_excel('New_Excel_File')

ValueError: No engine for filetype: ''

In [1]:
df

NameError: name 'df' is not defined

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
sal = pd.read_csv('Salaries.csv')
sal

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [4]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [5]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [6]:
len(sal['BasePay'])

148654

In [7]:
sum(sal['BasePay'])

nan

In [8]:
sal['BasePay'].sum()/len(sal['BasePay'])

66053.72928807836

In [9]:
sal['OvertimePay'].max()

245131.88

In [10]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']

Id     EmployeeName                   JobTitle    BasePay  OvertimePay  \
24  25  JOSEPH DRISCOLL  CAPTAIN, FIRE SUPPRESSION  140546.86     97868.77   

    OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  Notes  \
24  31909.28       NaN  270324.91         270324.91  2011    NaN   

           Agency  Status  
24  San Francisco     NaN

In [11]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [12]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [13]:
maxsal = sal['TotalPayBenefits'].max()
sal[sal['TotalPayBenefits'] == (maxsal)]

Id    EmployeeName                                        JobTitle  \
0   1  NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18          0.0  400184.25       NaN  567595.43         567595.43   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN

In [14]:
minsal = sal['TotalPayBenefits'].min()
sal[sal['TotalPayBenefits'] == (minsal)]

Id EmployeeName                    JobTitle  BasePay  OvertimePay  \
148653  148654    Joe Lopez  Counselor, Log Cabin Ranch      0.0          0.0   

        OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
148653   -618.13       0.0   -618.13           -618.13  2014    NaN   

               Agency  Status  
148653  San Francisco     NaN

In [16]:
sal.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

In [35]:
mbp = sal.groupby('Year').mean('BasePay')
mbp['BasePay']

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

In [38]:
sal['JobTitle'].nunique()

2159

In [41]:
mcj = sal['JobTitle'].value_counts()
mcj.head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [69]:
ooo = sal.groupby('Year')
ooo['JobTitle'].unique()

Year
2011    [GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORIT...
2012    [Lieutenant, Fire Suppression, Chief of Police...
2013    [Chief of Police, Chief, Fire Department, Batt...
2014    [Deputy Chief 3, Asst Med Examiner, Chief Inve...
Name: JobTitle, dtype: object

In [82]:
search = sal[sal['JobTitle'].str.contains('Chief', case = True, na = False)]
len(search)

423

In [89]:
yearcheck = sal[sal['Year']==2013]
yaercheck.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [1]:
import pandas as pd
import numpy as np

In [7]:
data = ['A','B','C','D']
df = pd.Series(data)
df

0    A
1    B
2    C
3    D
dtype: object

In [1]:
import pandas as pd
import numpy as np

In [2]:
sal = pd.read_csv('Salaries.csv')

In [3]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [4]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [6]:
sal.shape

(148654, 13)

In [15]:
sal.iloc[4]

Id                                                             5
EmployeeName                                     PATRICK GARDNER
JobTitle            DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
BasePay                                                 134401.6
OvertimePay                                               9737.0
OtherPay                                               182234.59
Benefits                                                     NaN
TotalPay                                               326373.19
TotalPayBenefits                                       326373.19
Year                                                        2011
Notes                                                        NaN
Agency                                             San Francisco
Status                                                       NaN
Name: 4, dtype: object

In [16]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [18]:
sal.loc['TotalPayBenefits', axis = 1]

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (1888564645.py, line 1)

In [24]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr[3]

3

In [26]:
arr[0:2] = 100

In [27]:
arr

array([100, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [34]:
partarr = arr[2:4]

In [35]:
partarr

array([2, 3])

In [36]:
partarr[:] = 100 

In [37]:
partarr

array([100, 100])

In [38]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [39]:
npartarr = arr[2:4].copy()

In [40]:
npartarr

array([100, 100])

In [41]:
npartarr[:]= 1

In [43]:
npartarr

array([1, 1])

In [29]:
import numpy as np
import pandas as pd

In [6]:
ser = pd.Series()
ser

Series([], dtype: object)

In [19]:
dict = {'Alex':18,'John':19,'Clark':20}

In [20]:
ser = pd.Series(dict)
ser

Alex     18
John     19
Clark    20
dtype: int64

In [23]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [26]:
df = pd.DataFrame(data = dict,index= dict)
df

Alex  John  Clark
Alex     18    19     20
John     18    19     20
Clark    18    19     20

In [28]:
lst = ['geeks','for','geeks']
df = pd.DataFrame(lst)
df

0
0  geeks
1    for
2  geeks

In [36]:
arr = np.arange(91,101)
arr

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [37]:
ser = pd.Series(arr)
ser

0     91
1     92
2     93
3     94
4     95
5     96
6     97
7     98
8     99
9    100
dtype: int32

In [40]:
lst = ['A','B','C','D','E','F']
lst

['A', 'B', 'C', 'D', 'E', 'F']

In [41]:
ser = pd.Series(lst)
ser

0    A
1    B
2    C
3    D
4    E
5    F
dtype: object

In [42]:
ser[4]

'E'

In [43]:
ser[:3]

0    A
1    B
2    C
dtype: object

In [44]:
ser[:]

0    A
1    B
2    C
3    D
4    E
5    F
dtype: object

In [45]:
ser[1:3]

1    B
2    C
dtype: object

In [46]:
ser = pd.Series(data=lst,index=['a','b','c','d','e','f'])

In [47]:
ser

a    A
b    B
c    C
d    D
e    E
f    F
dtype: object

In [49]:
ser['d']

'D'

In [51]:
ser['a':'d']

a    A
b    B
c    C
d    D
dtype: object

In [52]:
ser

a    A
b    B
c    C
d    D
e    E
f    F
dtype: object

In [53]:
ser.head()

a    A
b    B
c    C
d    D
e    E
dtype: object

In [63]:
df = pd.read_csv('nba.csv')
ser = pd.Series(df['Name'])
ser.head(10)

0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
5     Amir Johnson
6    Jordan Mickey
7     Kelly Olynyk
8     Terry Rozier
9     Marcus Smart
Name: Name, dtype: object

In [72]:
ser.iloc[3:6]

3      R.J. Hunter
4    Jonas Jerebko
5     Amir Johnson
Name: Name, dtype: object

In [70]:
ser[3:6]

3      R.J. Hunter
4    Jonas Jerebko
5     Amir Johnson
Name: Name, dtype: object

In [71]:
ser.iloc[3:6]

3      R.J. Hunter
4    Jonas Jerebko
5     Amir Johnson
Name: Name, dtype: object

In [77]:
df1 = pd.DataFrame(data=[1,3,5,7],index=('a','b','c','d'))
df2 = pd.DataFrame(data=[2,4,6,8],index=['a','b','d','e'])
print(df1)
print(df2)

   0
a  1
b  3
c  5
d  7
   0
a  2
b  4
d  6
e  8


In [82]:
add_df = df1.add(df2,fill_value=100)
add_df

0
a    3.0
b    7.0
c  105.0
d   13.0
e  108.0

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('nba.csv')

In [3]:
df

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
..             ...             ...     ...      ...   ...    ...     ...   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN   

               College     Salary  
0                Texas  7730337.0  
1            Marquette  6796117.0  
2    Boston University        NaN  
3        Georgia State  1148640.0  
4                  NaN  5000000.0  
..                 ...        ...  
453             Butler  2433333.0  
454                NaN   900000.0  
455                NaN  2900000.0  
456             Kansas   947276.0  
457                NaN        NaN  

[458 rows x 9 columns]

In [4]:
df1 = pd.read_csv('Salaries.csv')

In [5]:
df1

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [6]:
df

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
..             ...             ...     ...      ...   ...    ...     ...   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN   

               College     Salary  
0                Texas  7730337.0  
1            Marquette  6796117.0  
2    Boston University        NaN  
3        Georgia State  1148640.0  
4                  NaN  5000000.0  
..                 ...        ...  
453             Butler  2433333.0  
454                NaN   900000.0  
455                NaN  2900000.0  
456             Kansas   947276.0  
457                NaN        NaN  

[458 rows x 9 columns]

In [7]:
df.dropna(inplace=True)

In [11]:
before = df.dtypes
before

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [12]:
df['Salary'] = df['Salary'].astype(int)
df['Number'] = df['Number'].astype(str)

In [14]:
after = df.dtypes

In [15]:
before

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [16]:
after

Name         object
Team         object
Number       object
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary        int32
dtype: object

In [17]:
import pandas as pd

In [20]:
lst = [1,3,5,7,9]
s = pd.Series(lst, index=['a','b','c','d','e'])

In [21]:
s

a    1
b    3
c    5
d    7
e    9
dtype: int64

In [22]:
s.to_list()

[1, 3, 5, 7, 9]

In [2]:
# importing pandas module 
import pandas as pd 
 
# importing regex module
import re
   
# making data frame 
data = pd.read_csv("https://media.geeksforgeeks.org/wp-content/uploads/nba.csv") 
   
# removing null values to avoid errors 
data.dropna(inplace = True) 
 
# other series
other = data["Weight"]/10
 
# calling method and returning to new column
data["Age > Weight"]= data["Age"].gt(other)

In [3]:
other

0      18.0
1      23.5
3      18.5
6      23.5
7      23.8
       ... 
449    20.6
451    20.6
452    23.4
453    20.3
456    23.1
Name: Weight, Length: 364, dtype: float64

In [5]:
data["Age > Weight"].head()

0     True
1     True
3     True
6    False
7     True
Name: Age > Weight, dtype: bool